spring:
  datasource:
    master:
      password: suntek
      username: root
      url: jdbc:mysql://localhost:3306/test1?characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
      type: com.zaxxer.hikari.HikariDataSource
    cluster:
    - key: slave1
      password: suntek
      username: root
      url: jdbc:mysql://localhost:3306/test2?characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
      type: com.zaxxer.hikari.HikariDataSource

mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: spring.in.action.custom.multi.datasource.domain
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl